spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wxd898fcb01713c658
  mpSecret:
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: C:\Users\apollo\Documents\h5.p12
  notifyUrl: http:pipersell.natapp1.cc/sell/pay/notify
